# Generated by Django 3.0.4 on 2020-03-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_4',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
