from django.urls import path
from . import views

urlpatterns = [
    path('mine/',
         views.ManageCourseListView.as_view(),
         name='manage_course_list'),
    path('create/',
         views.CourseCreateView.as_view(),
         name='course_create'),
    path('<pk>/edit/',
         views.CourseUpdateView.as_view(),
         name='course_edit'),
    path('<pk>/delete/',
         views.CourseDeleteView.as_view(),
         name='course_delete'),
     path('<pk>/module/',
         views.CourseModuleUpdateView.as_view(),
         name='course_module_update'),
     path('<pk>/students/',
         views.CourseStudentsListView.as_view(),
         name='course_students'),
     path('module/<int:module_id>/content/<model_name>/create/',
          views.ContentCreateUpdateView.as_view(),
          name='module_content_create'),
     path('module/<int:module_id>/content/<model_name>/<id>',
          views.ContentCreateUpdateView.as_view(),
          name='module_content_update'),

     path('<pk>/test/',
         views.CourseTestUpdateView.as_view(),
         name='course_test_update'),
     path('<pk>/test/manage/',
         views.TestManageView.as_view(),
         name='course_tests_manage'),
     path('test/<int:test_id>/create/<question_type>/',
          views.QuestionCreateUpdateView.as_view(),
          name='test_question_create'),
     path('test/<int:test_id>/<question_type>/<id>/',
          views.QuestionCreateUpdateView.as_view(),
          name='test_question_change'),
     path('test/<int:test_id>/delete/<question_type>/<id>/',
          views.QuestionDeleteView.as_view(),
          name='test_question_delete'),
     path('test/<int:test_id>/',
          views.QuestionManageView.as_view(),
          name='test_question_update'),

     path('content/<int:id>/delete',
          views.ContentDeleteView.as_view(),
          name='module_content_delete'),
     path('module/<int:module_id>/',
          views.ModuleContentListView.as_view(),
          name='module_content_list'),
     path('module/order/',
          views.ModuleOrderView.as_view(),
          name='module_order'),
     path('content/order/',
          views.ContentOrderView.as_view(),
          name='content_order'),
     path('subject/<slug:subject>/',
          views.CourseListView.as_view(),
          name='course_list_subject'),
     path('<slug:slug>/',
          views.CourseDetailView.as_view(),
          name='course_detail'),

     path('student/grades/<course_id>/<student_id>/',
        views.TeacherStudentGradesView.as_view(),
        name='teacher_student_course_grades'),
]
