# Generated by Django 3.0.4 on 2020-04-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='learning_style',
            field=models.CharField(blank=True, choices=[('wzrokowiec', 'wzrokowiec'), ('słuchowiec', 'słuchowiec'), ('dotykowiec', 'dotykowiec'), ('kinestetyk', 'kinestetyl')], max_length=10, null=True),
        ),
    ]
