# Generated by Django 3.0.4 on 2020-05-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_module_learning_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='module',
            name='learning_style',
            field=models.CharField(choices=[('wzrokowiec', 'wzrokowiec'), ('słuchowiec', 'słuchowiec'), ('dotykowiec', 'dotykowiec'), ('kinestetyk', 'kinestetyk'), ('wszyscy', 'wszyscy')], max_length=10),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
