# Generated by Django 3.0.4 on 2020-05-29 12:29

import courses.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20200529_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionclosed',
            name='order',
            field=courses.fields.OrderField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortanswer',
            name='order',
            field=courses.fields.OrderField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionclosed',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Test'),
        ),
        migrations.AlterField(
            model_name='shortanswer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Test'),
        ),
    ]
