# Generated by Django 3.0.4 on 2020-05-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200529_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionclosed',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='shortanswer',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
