# Generated by Django 3.0.4 on 2020-05-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200529_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionclosed',
            name='answer',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
