# Generated by Django 3.0.4 on 2020-05-30 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_questionclosed_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='total',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
